### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by wiiremote5** [majorsopa/texture-packs#3]
thiss suck

**Comment by ballsballsballsballsballsballsballsball** [comment]
Hi

**Comment by ceilingfans** [comment]
![e1d3e4d35785f95b10bd5c5e886b060e](https://user-images.githubusercontent.com/65061212/120055072-5c241d80-c066-11eb-8c6a-395527dbeb3a.png)

**Comment by wiiremote5** [comment]
Lol it is a cat

**Comment by ceilingfans** [comment]
> Lol it is a cat

yeah it is a cat
![Periodic Table](https://user-images.githubusercontent.com/65061212/120055101-7f4ecd00-c066-11eb-86dd-3c8880dfb064.jpeg)

**Comment by sufficients** [comment]
Lol it is cat
