### ISSUE TITLE
new tp

### ISSUE THREAD

**Issue by ProtoMan8WasTaken** [majorsopa/texture-packs#5]
https://www.mediafire.com/file/1zm4li83qp8f10b/!+§5§lReverbV1.zip/file
https://www.mediafire.com/file/1zm4li83qp8f10b/!+§5§lReverbV1.zip/file
https://www.mediafire.com/file/1zm4li83qp8f10b/!+§5§lReverbV1.zip/file
https://www.mediafire.com/file/1zm4li83qp8f10b/!+§5§lReverbV1.zip/file
https://www.mediafire.com/file/1zm4li83qp8f10b/!+§5§lReverbV1.zip/file

**Comment by majorsopa** [comment]
why paste it so many times and make 2 issues

**Comment by majorsopa** [comment]
also @ProtoMan8WasTaken what version is this for?

**Comment by majorsopa** [comment]
bro the zip is empty lol

edit nvm windows is stupid

**Comment by majorsopa** [comment]
added
